---
- name: This playbook will iinstall tomcat and java and deploy the hello-world application
  hosts: myclients
  tasks: 
    - name: This task will install Java on your hosts
      become: yes
      become_user: root
      yum:
        name: java
        state: present
    - name: downloading the wget package
      get_url: 
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.zip
        dest: /home/ec2-user/